[package]
name = "kally"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Git-first package manager for Kalcite"
repository = "https://github.com/Kalcite-Engine/kally"
readme = "README.md"
keywords = ["kalcite", "package-manager", "git"]
categories = ["command-line-utilities", "development-tools"]

[build-dependencies]
kalcite-syntax = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "19bb1c1ba5419b3c2643ba521fe3c5b9cd09c9c6" }
kalcite-hir = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "19bb1c1ba5419b3c2643ba521fe3c5b9cd09c9c6" }
kalcite-mir = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "19bb1c1ba5419b3c2643ba521fe3c5b9cd09c9c6" }
kalcite-backend-rust = { git = "https://github.com/Kalcite-Engine/kalcite.git", rev = "19bb1c1ba5419b3c2643ba521fe3c5b9cd09c9c6" }
